name: 'Announce on Nostr'
description: 'Announce uploaded file on Nostr network'
branding:
  color: orange
  icon: radio
inputs:
  host:
    description: 'The Blossom host server'
    required: true
  relay:
    description: 'Nostr relay host'
    required: true
  file-hash:
    description: 'The hash of the uploaded file'
    required: true
  nsec:
    description: 'Nostr private key (KEEP SECRET!)'
    required: true
outputs:
  event-id:
    description: 'The Nostr event ID of the announcement'
runs:
  using: node20 # Or node16
  main: dist/index.js # Path to your compiled JavaScript file
