name: 'Announce on Nostr'
description: 'Announce uploaded file on Nostr network'
branding:
  color: orange
  icon: radio
inputs:
  host:
    description: 'The Blossom host server'
    required: true
  relay:
    description: 'Nostr relay host'
    required: true
  blossom-hash:
    description: 'Hash of uploaded file from Blossom'
    required: true
  nsec:
    description: 'Nostr secret key to sign events with'
    required: true
outputs:
  event-id:
    description: 'The Nostr event ID of the announcement'
runs:
  using: 'node20'
  main: 'dist/index.js'
