name: Test Nostr Announcement Action

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-announce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Create dummy file
        run: |
          echo "This is a test file" > dummy.txt
      - name: Upload dummy to Blossom
        id: upload
        uses: c03rad0r/upload-blossom-action@6e15ba1abd32810145753929956df0c32c710089
        with:
          host: 'https://blossom.swissdash.site/'
          filePath: './dummy.txt'
      - name: Announce on Nostr
        uses: ./
        with:
          host: 'https://blossom.swissdash.site/'
          relay: 'wss://orangesync.tech'
          blossom-hash: ${{ steps.upload.outputs.blossom-hash }}
          nsec: ${{ secrets.NOSTR_PRIVATE_KEY }}
